# http://www.appveyor.com/docs/appveyor-yml

branches:
  only:
    - master
  except:
    - gh-pages

environment:
  global:
    CYG_ROOT: C:/cygwin

install:
#  - appveyor DownloadFile "http://cygwin.com/setup-%CYG_ARCH%.exe" -FileName "%CYG_ROOT%\setup-x86.exe"
  - ps: '(new-object net.webclient).DownloadString("https://aantron.github.io/binaries/cygwin/x86/ocaml/4.02/install.ps1") | PowerShell -Command -'
  - ps: '(new-object net.webclient).DownloadString("https://aantron.github.io/binaries/cygwin/x86/camlp4/4.02/install.ps1") | PowerShell -Command -'
  - ps: '(new-object net.webclient).DownloadString("https://aantron.github.io/binaries/cygwin/x86/opam/1.2/install.ps1") | PowerShell -Command -'
  - '%CYG_ROOT%\bin\bash -lc "cygcheck -dc cygwin"'
  - '%CYG_ROOT%\bin\bash -lc "echo \"OCaml version `ocamlc -version`\""'

build_script:
  - 'echo Build in "%APPVEYOR_BUILD_FOLDER%"'
  - '%CYG_ROOT%/bin/bash -l "%APPVEYOR_BUILD_FOLDER%/appveyor_build.sh"'
