# http://www.appveyor.com/docs/appveyor-yml

branches:
  only:
    - master
  except:
    - gh-pages

platform:
  - x86

environment:
  FORK_USER: ocaml
  FORK_BRANCH: master
  CYG_ROOT: C:\cygwin64
  PINS: fileutils:https://github.com/gildor478/ocaml-fileutils.git

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/$env:FORK_USER/ocaml-ci-scripts/$env:FORK_BRANCH/appveyor-install.ps1"))

build_script:
  - call %CYG_ROOT%\bin\bash.exe -l %APPVEYOR_BUILD_FOLDER%\appveyor-opam.sh

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/7ff53153d7d00ed61e3d
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true

artifacts:
  - path: setup.log
    name: setup.log

